CREATE TABLE projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    short_description VARCHAR(1000) NOT NULL,
    description VARCHAR(5000),
    cover_image_url TEXT,
    github_url TEXT,
    demo_url TEXT,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO projects (
    id,
    title,
    slug,
    short_description,
    description,
    cover_image_url,
    github_url,
    demo_url,
    display_order,
    created_at
) VALUES
      (
          1,
          'Meu Portfólio',
          'meu-portfolio',
          'Portfólio pessoal desenvolvido com React, TypeScript e Tailwind CSS, integrado a uma API própria em Spring Boot.',
          'Aplicação frontend do meu portfólio pessoal desenvolvido com React, TypeScript e Tailwind CSS, consumindo API própria construída em Spring Boot. O projeto apresenta informações profissionais, habilidades, experiência e projetos desenvolvidos, com integração dinâmica ao backend e armazenamento de imagens em Cloudinary.',
          'https://res.cloudinary.com/dzzsbck9z/image/upload/v1779833351/sdi8mymfcmxvtywyok52.png',
          'https://github.com/ronneyrv/portfolio-web',
          'https://portfolio-ronney.vercel.app/',
          10,
          '2026-06-08 17:33:52.425045'
      ),
      (
          2,
          'API Portfolio',
          'api-portfolio',
          'API REST desenvolvida com Spring Boot para gerenciamento de projetos do portfólio.',
          'API REST desenvolvida com Spring Boot para gerenciar os projetos do meu Portifólio, com documentação SWAGGER.
      Java | Spring Boot | Data JPA | PostgreSQL | Docker',
          'https://res.cloudinary.com/dzzsbck9z/image/upload/v1779811893/npd02j9n6fzwfslrajbv.png',
          'https://github.com/ronneyrv/portfolio-api',
          'https://portfolio-api-5kec.onrender.com/swagger-ui/index.html',
          20,
          '2026-06-08 17:33:52.425045'
      ),
      (
          3,
          'Netflix Clone — Frontend Replication',
          'netflix-clone-frontend-replication',
          'Réplica responsiva da interface da Netflix, desenvolvida com React, integração com API e componentização de frontend.',
          'Este projeto é uma reprodução fiel e responsiva da interface da Netflix, desenvolvida com o objetivo de consolidar conceitos avançados de desenvolvimento frontend, consumo de APIs RESTful e componentização. O projeto consome dados reais de filmes e séries, oferecendo uma experiência de navegação fluida, moderna e sem gargalos de performance.',
          'https://res.cloudinary.com/dzzsbck9z/image/upload/v1779812451/js5lywbz2bwtffxlucmo.png',
          'https://github.com/ronneyrv/clone_Netflix',
          'https://clone-netflix-snowy-ten.vercel.app',
          30,
          '2026-06-08 17:33:52.425045'
      ),
      (
          4,
          'API - Loja de Roupas Física',
          'api-loja-de-roupas-fisica',
          'API REST desenvolvida com Node.js, Express e MySQL para gerenciamento de uma loja física de roupas.',
          'Trabalho final da turma FS44 - Digital College. O sistema foi desenvolvido utilizando uma stack moderna e eficiente, combinando ferramentas que garantem desempenho, segurança e fácil manutenção.
      JavaScript | Node | Express | MySQL',
          'https://res.cloudinary.com/dzzsbck9z/image/upload/v1779812183/n9uaxzgysd0uzahyikgn.png',
          'https://github.com/ronneyrv/API-Loja-de-Roupas-Fisica',
          'https://portfolio-api-5kec.onrender.com/swagger-ui/index.html',
          40,
          '2026-06-08 17:33:52.425045'
      ),
      (
          5,
          'FAQ Manager',
          'faq-manager',
          'Aplicação web para gerenciamento de perguntas frequentes, desenvolvida com React e Material UI.',
          'Aplicação web para gerenciamento de perguntas frequentes (FAQ), desenvolvida com React e Material UI. O projeto permite visualizar, adicionar, editar e remover perguntas através de uma interface moderna e responsiva.',
          'https://res.cloudinary.com/dzzsbck9z/image/upload/v1779812547/gb8kvoj7rtsmuehyplix.png',
          'https://github.com/ronneyrv/faq-manager',
          'https://faq-manager-black.vercel.app/',
          50,
          '2026-06-08 17:33:52.425045'
      ),
      (
          6,
          'Gerenciador de Tarefas',
          'gerenciador-de-tarefas',
          'Aplicação responsiva para gerenciamento e organização de tarefas do dia a dia.',
          'Aplicação web para gerenciamento de tarefas desenvolvida para organizar atividades diárias de forma simples e intuitiva. O sistema permite criar, editar, concluir e remover tarefas através de uma interface prática e responsiva.',
          'https://res.cloudinary.com/dzzsbck9z/image/upload/v1779812638/ubr9gh4azdyu0ejmdv14.png',
          'https://github.com/ronneyrv/gerenciador-de-tarefas',
          'https://gerenciador-de-tarefas-liart.vercel.app',
          60,
          '2026-06-08 17:33:52.425045'
      );

ALTER TABLE projects
    ALTER COLUMN id RESTART WITH 7;
