CREATE TABLE project_images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL,
    image_url TEXT NOT NULL,
    display_order INTEGER NOT NULL,
    alt_text VARCHAR(500),

    CONSTRAINT fk_project_images_project
        FOREIGN KEY (project_id)
            REFERENCES projects (id)
);